# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\Ui_display_settings_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DisplaySettingsWidget(object):
    def setupUi(self, DisplaySettingsWidget):
        DisplaySettingsWidget.setObjectName("DisplaySettingsWidget")
        DisplaySettingsWidget.resize(400, 301)
        self.verticalLayout = QtWidgets.QVBoxLayout(DisplaySettingsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.colormap_groupbox = QtWidgets.QGroupBox(DisplaySettingsWidget)
        self.colormap_groupbox.setObjectName("colormap_groupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.colormap_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.colormap_groupbox)
        self.transparency_groupbox = QtWidgets.QGroupBox(DisplaySettingsWidget)
        self.transparency_groupbox.setObjectName("transparency_groupbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.transparency_groupbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addWidget(self.transparency_groupbox)
        self.thresholding_groupbox = QtWidgets.QGroupBox(DisplaySettingsWidget)
        self.thresholding_groupbox.setObjectName("thresholding_groupbox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.thresholding_groupbox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout.addWidget(self.thresholding_groupbox)

        self.retranslateUi(DisplaySettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(DisplaySettingsWidget)

    def retranslateUi(self, DisplaySettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        DisplaySettingsWidget.setWindowTitle(_translate("DisplaySettingsWidget", "Frame"))
        self.colormap_groupbox.setTitle(_translate("DisplaySettingsWidget", "Colormap"))
        self.transparency_groupbox.setTitle(_translate("DisplaySettingsWidget", "Transparency"))
        self.thresholding_groupbox.setTitle(_translate("DisplaySettingsWidget", "Thresholding"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DisplaySettingsWidget = QtWidgets.QFrame()
    ui = Ui_DisplaySettingsWidget()
    ui.setupUi(DisplaySettingsWidget)
    DisplaySettingsWidget.show()
    sys.exit(app.exec_())
