# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\threshold_widget_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_threshold_widget_frame(object):
    def setupUi(self, threshold_widget_frame):
        threshold_widget_frame.setObjectName("threshold_widget_frame")
        threshold_widget_frame.resize(417, 286)
        self.verticalLayout = QtWidgets.QVBoxLayout(threshold_widget_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plot_frame = QtWidgets.QFrame(threshold_widget_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_frame.sizePolicy().hasHeightForWidth())
        self.plot_frame.setSizePolicy(sizePolicy)
        self.plot_frame.setMinimumSize(QtCore.QSize(100, 0))
        self.plot_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.plot_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plot_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_frame.setObjectName("plot_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.plot_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addWidget(self.plot_frame)
        self.edits_frame = QtWidgets.QFrame(threshold_widget_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edits_frame.sizePolicy().hasHeightForWidth())
        self.edits_frame.setSizePolicy(sizePolicy)
        self.edits_frame.setMinimumSize(QtCore.QSize(100, 50))
        self.edits_frame.setMaximumSize(QtCore.QSize(1677215, 50))
        self.edits_frame.setObjectName("edits_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.edits_frame)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.min_display_edit = QtWidgets.QLineEdit(self.edits_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_display_edit.sizePolicy().hasHeightForWidth())
        self.min_display_edit.setSizePolicy(sizePolicy)
        self.min_display_edit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.min_display_edit.setObjectName("min_display_edit")
        self.horizontalLayout_2.addWidget(self.min_display_edit)
        self.label = QtWidgets.QLabel(self.edits_frame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.edits_frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.max_display_edit = QtWidgets.QLineEdit(self.edits_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_display_edit.sizePolicy().hasHeightForWidth())
        self.max_display_edit.setSizePolicy(sizePolicy)
        self.max_display_edit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.max_display_edit.setObjectName("max_display_edit")
        self.horizontalLayout_2.addWidget(self.max_display_edit)
        self.verticalLayout.addWidget(self.edits_frame)

        self.retranslateUi(threshold_widget_frame)
        QtCore.QMetaObject.connectSlotsByName(threshold_widget_frame)

    def retranslateUi(self, threshold_widget_frame):
        _translate = QtCore.QCoreApplication.translate
        threshold_widget_frame.setWindowTitle(_translate("threshold_widget_frame", "Frame"))
        self.min_display_edit.setText(_translate("threshold_widget_frame", "0"))
        self.label.setText(_translate("threshold_widget_frame", "Min"))
        self.label_2.setText(_translate("threshold_widget_frame", "Max"))
        self.max_display_edit.setText(_translate("threshold_widget_frame", "1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    threshold_widget_frame = QtWidgets.QFrame()
    ui = Ui_threshold_widget_frame()
    ui.setupUi(threshold_widget_frame)
    threshold_widget_frame.show()
    sys.exit(app.exec_())
